app = "kidslearn"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  FrontendBaseUrl = "https://kidslearn.fly.dev"
  GoogleAuth__ParentFrontendCallbackUrl = "https://kidslearn.fly.dev/login/parent/google/callback"
  GoogleAuth__ChildFrontendCallbackUrl = "https://kidslearn.fly.dev/login/child/google/callback"
  GoogleAuth__UnifiedFrontendCallbackUrl = "https://kidslearn.fly.dev/login/google/unified/callback"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
